"""Lazy public API for ordinary, assembly-biased, and component IA-HOD tools."""

from __future__ import annotations

from typing import Any

from ia_analysis._lazy_imports import ExportMap, export_names, load_export

_EXPORTS: ExportMap = {
    "HODCatalog": ("ia_analysis.hod.catalog", "HODCatalog"),
    "standardize_hod_catalog": ("ia_analysis.hod.catalog", "standardize_hod_catalog"),
    "validate_hod_catalog": ("ia_analysis.hod.catalog", "validate_hod_catalog"),
    "infer_central_satellite_flags": ("ia_analysis.hod.catalog", "infer_central_satellite_flags"),
    "select_galaxy_sample": ("ia_analysis.hod.catalog", "select_galaxy_sample"),
    "join_halo_galaxy_properties": ("ia_analysis.hod.catalog", "join_halo_galaxy_properties"),
    "HODMeasurement": ("ia_analysis.hod.statistics", "HODMeasurement"),
    "measure_hod": ("ia_analysis.hod.statistics", "measure_hod"),
    "measure_central_hod": ("ia_analysis.hod.statistics", "measure_central_hod"),
    "measure_satellite_hod": ("ia_analysis.hod.statistics", "measure_satellite_hod"),
    "measure_total_hod": ("ia_analysis.hod.statistics", "measure_total_hod"),
    "measure_occupation_distribution": ("ia_analysis.hod.statistics", "measure_occupation_distribution"),
    "measure_satellite_fraction": ("ia_analysis.hod.statistics", "measure_satellite_fraction"),
    "measure_number_density": ("ia_analysis.hod.statistics", "measure_number_density"),
    "measure_xi_gg": ("ia_analysis.hod.statistics", "measure_xi_gg"),
    "measure_omega_ed": ("ia_analysis.hod.statistics", "measure_omega_ed"),
    "measure_eta_ee": ("ia_analysis.hod.statistics", "measure_eta_ee"),
    "measure_pairwise_ia": ("ia_analysis.hod.statistics", "measure_pairwise_ia"),
    "zheng_central_occupation": ("ia_analysis.hod.models", "zheng_central_occupation"),
    "zheng_satellite_occupation": ("ia_analysis.hod.models", "zheng_satellite_occupation"),
    "zheng_total_occupation": ("ia_analysis.hod.models", "zheng_total_occupation"),
    "predict_zheng_hod": ("ia_analysis.hod.models", "predict_zheng_hod"),
    "fit_zheng_hod": ("ia_analysis.hod.models", "fit_zheng_hod"),
    "hod_chi2": ("ia_analysis.hod.models", "hod_chi2"),
    "decorated_central_occupation": ("ia_analysis.hod.models", "decorated_central_occupation"),
    "decorated_satellite_occupation": ("ia_analysis.hod.models", "decorated_satellite_occupation"),
    "decorated_hod_prediction": ("ia_analysis.hod.models", "decorated_hod_prediction"),
    "standardize_secondary_property_at_fixed_mass": (
        "ia_analysis.hod.assembly", "standardize_secondary_property_at_fixed_mass"
    ),
    "split_by_secondary_property_quantiles": ("ia_analysis.hod.assembly", "split_by_secondary_property_quantiles"),
    "measure_assembly_hod": ("ia_analysis.hod.assembly", "measure_assembly_hod"),
    "split_by_environment_quantiles": ("ia_analysis.hod.environment", "split_by_environment_quantiles"),
    "measure_environment_hod": ("ia_analysis.hod.environment", "measure_environment_hod"),
    "split_by_concentration_quantiles": ("ia_analysis.hod.concentration", "split_by_concentration_quantiles"),
    "measure_concentration_hod": ("ia_analysis.hod.concentration", "measure_concentration_hod"),
    "measure_radial_profile_hod": ("ia_analysis.hod.phase_space", "measure_radial_profile_hod"),
    "measure_velocity_anisotropy_hod": ("ia_analysis.hod.phase_space", "measure_velocity_anisotropy_hod"),
    "measure_binding_energy_layer_occupation": (
        "ia_analysis.hod.phase_space", "measure_binding_energy_layer_occupation"
    ),
    "measure_phase_space_hod": ("ia_analysis.hod.phase_space", "measure_phase_space_hod"),
    "measure_phase_space_assembly_bias": ("ia_analysis.hod.phase_space", "measure_phase_space_assembly_bias"),
    "measure_host_axis_phase_space_alignment": (
        "ia_analysis.hod.phase_space", "measure_host_axis_phase_space_alignment"
    ),
    "safe_unit_vector": ("ia_analysis.hod.ia_reference", "safe_unit_vector"),
    "normalize_vectors": ("ia_analysis.hod.ia_reference", "normalize_vectors"),
    "alignment_cos2_minus_one_third": ("ia_analysis.hod.ia_reference", "alignment_cos2_minus_one_third"),
    "resolve_reference_vectors": ("ia_analysis.hod.ia_reference", "resolve_reference_vectors"),
    "build_reference_bank": ("ia_analysis.hod.ia_reference", "build_reference_bank"),
    "IAComponentMeasurement": ("ia_analysis.hod.ia_measurements", "IAComponentMeasurement"),
    "measure_reference_alignment": ("ia_analysis.hod.ia_measurements", "measure_reference_alignment"),
    "measure_alignment_hod_components": ("ia_analysis.hod.ia_measurements", "measure_alignment_hod_components"),
    "measure_central_host_alignment": ("ia_analysis.hod.ia_measurements", "measure_central_host_alignment"),
    "measure_central_tidal_alignment": ("ia_analysis.hod.ia_measurements", "measure_central_tidal_alignment"),
    "measure_satellite_radial_alignment": ("ia_analysis.hod.ia_measurements", "measure_satellite_radial_alignment"),
    "measure_satellite_host_alignment": ("ia_analysis.hod.ia_measurements", "measure_satellite_host_alignment"),
    "measure_satellite_subhalo_alignment": ("ia_analysis.hod.ia_measurements", "measure_satellite_subhalo_alignment"),
    "measure_satellite_tidal_alignment": ("ia_analysis.hod.ia_measurements", "measure_satellite_tidal_alignment"),
    "measure_satellite_velocity_alignment": ("ia_analysis.hod.ia_measurements", "measure_satellite_velocity_alignment"),
    "measure_satellite_spin_alignment": ("ia_analysis.hod.ia_measurements", "measure_satellite_spin_alignment"),
    "measure_binding_layer_alignment": ("ia_analysis.hod.ia_measurements", "measure_binding_layer_alignment"),
    "measure_figure_rotation_alignment": ("ia_analysis.hod.ia_measurements", "measure_figure_rotation_alignment"),
    "measure_mass_radius_alignment_grid": ("ia_analysis.hod.ia_measurements", "measure_mass_radius_alignment_grid"),
    "measure_sample_dependent_ia_hod": ("ia_analysis.hod.ia_measurements", "measure_sample_dependent_ia_hod"),
    "measure_assembly_dependent_ia_hod": ("ia_analysis.hod.ia_measurements", "measure_assembly_dependent_ia_hod"),
    "IAStrengthParameters": ("ia_analysis.hod.ia_models", "IAStrengthParameters"),
    "IAComponentModel": ("ia_analysis.hod.ia_models", "IAComponentModel"),
    "ComponentIAHODModel": ("ia_analysis.hod.ia_models", "ComponentIAHODModel"),
    "constant_alignment_strength": ("ia_analysis.hod.ia_models", "constant_alignment_strength"),
    "mass_powerlaw_alignment_strength": ("ia_analysis.hod.ia_models", "mass_powerlaw_alignment_strength"),
    "radius_powerlaw_alignment_strength": ("ia_analysis.hod.ia_models", "radius_powerlaw_alignment_strength"),
    "mass_radius_alignment_strength": ("ia_analysis.hod.ia_models", "mass_radius_alignment_strength"),
    "assembly_modulated_alignment_strength": ("ia_analysis.hod.ia_models", "assembly_modulated_alignment_strength"),
    "sample_modulated_alignment_strength": ("ia_analysis.hod.ia_models", "sample_modulated_alignment_strength"),
    "layer_modulated_alignment_strength": ("ia_analysis.hod.ia_models", "layer_modulated_alignment_strength"),
    "predict_ia_component": ("ia_analysis.hod.ia_models", "predict_ia_component"),
    "predict_ia_component_grid": ("ia_analysis.hod.ia_models", "predict_ia_component_grid"),
    "combine_ia_components": ("ia_analysis.hod.ia_models", "combine_ia_components"),
    "predict_orientation_moments": ("ia_analysis.hod.ia_forward", "predict_orientation_moments"),
    "sample_orientations_from_reference": ("ia_analysis.hod.ia_forward", "sample_orientations_from_reference"),
    "assign_mock_orientations": ("ia_analysis.hod.ia_forward", "assign_mock_orientations"),
    "ia_component_chi2": ("ia_analysis.hod.fitting", "ia_component_chi2"),
    "fit_ia_component_model": ("ia_analysis.hod.fitting", "fit_ia_component_model"),
    "fit_joint_hod_assembly_ia": ("ia_analysis.hod.fitting", "fit_joint_hod_assembly_ia"),
    "diagonal_covariance": ("ia_analysis.hod.covariance", "diagonal_covariance"),
    "bootstrap_measurement": ("ia_analysis.hod.covariance", "bootstrap_measurement"),
    "jackknife_measurement": ("ia_analysis.hod.covariance", "jackknife_measurement"),
    "regularize_covariance": ("ia_analysis.hod.covariance", "regularize_covariance"),
    "save_hod_measurement_hdf5": ("ia_analysis.hod.io", "save_hod_measurement_hdf5"),
    "load_hod_measurement_hdf5": ("ia_analysis.hod.io", "load_hod_measurement_hdf5"),
    "save_ia_component_hdf5": ("ia_analysis.hod.io", "save_ia_component_hdf5"),
    "load_ia_component_hdf5": ("ia_analysis.hod.io", "load_ia_component_hdf5"),
    "measurement_to_dataframe": ("ia_analysis.hod.io", "measurement_to_dataframe"),
    "measurement_from_dataframe": ("ia_analysis.hod.io", "measurement_from_dataframe"),
    "plot_hod": ("ia_analysis.hod.plotting", "plot_hod"),
    "plot_hod_by_sample": ("ia_analysis.hod.plotting", "plot_hod_by_sample"),
    "plot_assembly_hod": ("ia_analysis.hod.plotting", "plot_assembly_hod"),
    "plot_environment_hod": ("ia_analysis.hod.plotting", "plot_environment_hod"),
    "plot_concentration_hod": ("ia_analysis.hod.plotting", "plot_concentration_hod"),
    "plot_phase_space_hod": ("ia_analysis.hod.plotting", "plot_phase_space_hod"),
    "plot_alignment_component": ("ia_analysis.hod.plotting", "plot_alignment_component"),
    "plot_mass_radius_alignment_grid": ("ia_analysis.hod.plotting", "plot_mass_radius_alignment_grid"),
    "plot_assembly_dependent_alignment": ("ia_analysis.hod.plotting", "plot_assembly_dependent_alignment"),
    "plot_ia_component_comparison": ("ia_analysis.hod.plotting", "plot_ia_component_comparison"),
    "plot_pairwise_omega_eta": ("ia_analysis.hod.plotting", "plot_pairwise_omega_eta"),
}

__all__ = export_names(_EXPORTS)


def __getattr__(name: str) -> Any:
    """Resolve HOD and IA-HOD helpers lazily."""
    return load_export(_EXPORTS, name)
